# Generated by Django 2.0 on 2020-09-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('license_no', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact_no', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[(1, 'Debit'), (2, 'Credit')], max_length=250)),
                ('transaction_amount', models.CharField(max_length=250)),
                ('transaction_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=250)),
                ('comapny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_no', models.CharField(max_length=250)),
                ('ifsc_no', models.CharField(max_length=250)),
                ('comapny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('request_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('joining_date', models.DateField()),
                ('phone', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_no', models.CharField(max_length=250)),
                ('ifsc_no', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_date', models.DateField()),
                ('salary_amount', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salt_name', models.CharField(max_length=100)),
                ('salt_qty', models.IntegerField()),
                ('salt_qty_type', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('medical_type', models.CharField(max_length=250)),
                ('buy_price', models.CharField(max_length=250)),
                ('sell_price', models.CharField(max_length=250)),
                ('c_gst', models.CharField(max_length=250)),
                ('s_gst', models.CharField(max_length=250)),
                ('batch_no', models.CharField(max_length=250)),
                ('shelf_no', models.CharField(max_length=250)),
                ('exp_date', models.DateField()),
                ('mfg_date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('in_stoc_total', models.IntegerField()),
                ('qty_in_strip', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('comapny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Company')),
            ],
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medicine'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='medicine_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medicine'),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medicine'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Customer'),
        ),
    ]
